const classes = {
    '100Limit': 'Ограничение скорости 100',
    '10Limit': 'Ограничение скорости 10',
    '1sideRoad': '1sideRoad', 
    '1sideRoadRight': '1sideRoadRight',
    '20Limit': 'Ограничение скорости 20',
    '30Limit': 'Ограничение скорости 30',
    '40Limit': 'Ограничение скорости 40',
    '50Limit': 'Ограничение скорости 50',
    '60Limit': 'Ограничение скорости 60',
    '70Limit': 'Ограничение скорости 70',
    '80Limit': 'Ограничение скорости 80',
    'BusRoad': 'Полоса для автобусов',
    'BusStop': 'Автобусная остановка',
    'Deti': 'Дети',
    'Forbidden': 'Движение запрещено',
    'Force': 'Force',
    'ForwardAndLeftPolosa': 'ForwardAndLeftPolosa',
    'ForwardAndRightPolosa': 'ForwardAndRightPolosa',
    'ForwardPolosa': 'ForwardPolosa',
    'Information': 'Информационный знак',
    'LeftAndRightPolosa': 'LeftAndRightPolosa',
    'LeftPolosa': 'LeftPolosa',
    'NoPark': 'Стоянка запрещена',
    'NoParkAndStop': 'Остановка запрещена',
    'NoRight': 'Поворот направо запрещен',
    'Parking': 'Парковка',
    'Perehod': 'Пешеходный переход',
    'RightPolosa': 'RightPolosa',
    'RingRoad': 'Круговое движение',
    'Special': 'Special',
    'Stop': 'Стоп',
    'Tramvai': 'Трамвай',
    'Tupik': 'Тупик',
    'Ustupi': 'Уступи дорогу',
    'Warning': 'Предупреждающий знак',
    'end1sideRoad': 'end1sideRoad',
    'endmain': 'Конец главной дороги',
    'mainRoad': 'Главная дорога',
    'noLeft': 'Поворот налево запрещен',
    'noRide': 'Движение запрещено',
    'objezdLeft': 'Объезд слева',
    'objezdLeftRight': 'Объезд слева или справа',
    'objezdRight': 'Объезд справа',
    'onlyForward': 'Движение прямо',
    'onlyForwardAndLeft': 'Движение прямо или налево',
    'onlyForwardAndRight': 'Движение прямо или направо',
    'onlyLeft': 'Движение налево',
    'onlyRight': 'Движение направо',
    'onlyRightLeft': 'Движение налево или направо'
}

export const classToText = (cls) => {
    return classes[cls]
}